### ISSUE TITLE
[Bug]: Cannot define a function-like #define

### ISSUE THREAD

**Issue by mcesar-rlacruz** [Open-CMSIS-Pack/cmsis-toolbox#128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Adding a function-like define in `<project_name>.cproject.yml` with, for example (the last two):
```
      define:
        - MANUFACTURER: STM
        - FAMILY: STM32L4
        - DEVICE: L432KC
        - MC_MBED_NO_BUSINOUT
        - "_LIBCPP_VERBOSE_ABORT(...)": "((void)0)"
        - "_LIBCPP_VERBOSE_ABORT(...)="
```
results in all tokens converted to defines in `compile_commands.json`:
```
-D_LIBCPP_VERBOSE_ABORT -D( -D... -D) -D= -D( -D( -Dvoid -D) -D0 -D)
-D_LIBCPP_VERBOSE_ABORT -D( -D... -D)
```
Usage of `'`, `"`, singled or tripled, makes no difference.

### Expected Behavior

Such function-like macros should be added to the command line with:
```
-D"_LIBCPP_VERBOSE_ABORT(...)=((void)0)"
-D"_LIBCPP_VERBOSE_ABORT(...)="
```

### Steps To Reproduce

Add a function-like macro to file `<project_name>.cproject.yml`, for example:
```
      define:
        - "_LIBCPP_VERBOSE_ABORT(...)": "((void)0)"
        - "_LIBCPP_VERBOSE_ABORT(...)="
```
Then build.

### Affected tools

- [ ] cbuild
- [ ] cbuild-gen
- [ ] cpackget
- [ ] csolution
- [ ] packchk
- [ ] svdconv

### Affected operating systems

- [ ] Windows amd64
- [ ] Windows arm64
- [ ] Linux amd64
- [ ] Linux arm64
- [ ] MacOS amd64
- [ ] MacOS arm64

### Environment

- Windows 11 Enterprise 22H2
- Visual Studio Code + MDK with cmsis-toolbox 2.3.0
