### ISSUE TITLE
[Bug ?] "executes:" not handled correctly

### ISSUE THREAD

**Issue by saperlot** [Open-CMSIS-Pack/cmsis-toolbox#168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Unusable feature

Post Build scripts are not executed corretly. 

### Current Behavior

For example:

Included in csolution.yml:
```yml 
 executes:
    - execute: include CRC
      run: somebat.bat $input$ $output$
      always:
      input:
        - $hex()$
      output:
        - $hex()$_crc
      for-context:
        - .Debug
```

- when `cbuild *** --context-set --context ***.Debug***` is issued, the script wont execute.
- when no context was set with cbuild it executes on Debug context build.

Now if we remove the for-context in executes: config:

- when building with --context, the script wont execute.
- when no context was set with cbuild it executes only on Debug context build.

Now if we set the for-context to - .Release in executes: config:

- when building with  `--context ***-Release+*** `, error appears: 
error csolution: context "****.Debug+****" referenced by access sequence 'hex' does not exist or is not selected
- when building without context set, it executes with hex files in the Debug output folder. 

 --> So executes is not usable, which is a neccessary feature, therefore i've set it as a blocker

Another issue is, that build script execution direction is tmp/  I would assume that base directory to be on root. 

### Expected Behavior

Executes handled correctly. 

### Steps To Reproduce

--> see current behavior

### Affected tools

- [X] cbuild
- [ ] cbuild2cmake
- [ ] cpackget
- [ ] csolution
- [ ] packchk
- [ ] svdconv

### Affected operating systems

- [X] Windows amd64
- [ ] Windows arm64
- [ ] Linux amd64
- [ ] Linux arm64
- [ ] MacOS amd64
- [ ] MacOS arm64

### Environment

Windows 11
cmsis-toolbox: 2.5.0
