### ISSUE TITLE
[Enhancement] CMSIS-Toolbox artifact shall contain a manifest file

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/cmsis-toolbox#184]
Purpose of the manifest file:
- filename includes the version of the CMSIS-Toolbox 
- content lists the included tools and their versions
- optionally show sha256 checksum of binaries.

**Comment by soumeh01** [comment]
Thanks for raising this. Adding a manifest file with the specified details sounds feasible. However, I’d like to clarify a few points to ensure I understand correctly:

1. Each released CMSIS-Toolbox artifact (OS and Arch specific) will have a corresponding manifest file, which will be bundled within the release. Since each OS-Arch specific binary has its own sha256.

2. For the manifest file format, I suggest using YAML (named `manifest.yml`) due to its readability and popularity in DevOps and cloud environments. For example:

    ```yaml
    ---
    name: CMSIS-Toolbox
    version: 2.7.0
    binaries:
      cbuild:
        path: bin/cbuild
        version: 1.2.3
        sha256: d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2
      csolution:
        path: bin/csolution
        version: 1.2.2
        sha256: e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3
      ...
    ```

3. Currently, some released binaries, such as those under `devtools`, lack checksums. These will need to be added in the release process for their respective repositories. Additionally, CMSIS-Toolbox should read and include this information in the manifest file.
