### ISSUE TITLE
missing compile options (-g -O) for files in sub-groups

### ISSUE THREAD

**Issue by andbararm** [Open-CMSIS-Pack/cmsis-toolbox#195]
**Describe the bug**
When adding files to a cproject file in nested sub-groups like this:
```
  groups:
    - group: Source Files
      groups:
      - group: Main Files
        files:
        - file: ./main_AB.c
```
then during the build, options -g (Debug Information) and -O (Optimization) are missing. As a consequence, for such a module it is not possible to set breakpoints, due to the missing debug information.
When not using nested sub-groups like this:
```
  groups:
    - group: Source Files
      files:
        - file: ./main_AB.c
```
the named options are there. The difference can be seen in build related files, like in build.ninja or the compile_commands.json.

**To Reproduce**
You can use the attached project. It can be opened in uVision or Keil Studio. Then build it and check named files for the missing compiler options. Like in compile_commands.json, main_AB.c is missing -g -O0, while system_DS_CM3.c is compiled with  -g -O0.
[Test_Solution.zip](https://github.com/user-attachments/files/17618352/Test_Solution.zip)

**Expected behavior**
Also when putting source files in a sub-group, it should get all the compiler options like other files not in sub groups or also from other CMSIS components used in the project.

**Environment (please complete the following information):**

CBuild version: 2.6.1
