### ISSUE TITLE
[Bug]: Access sequence $Bname$ contains also vendor prefix before 'Bname'

### ISSUE THREAD

**Issue by RobertRostohar** [Open-CMSIS-Pack/cmsis-toolbox#205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Access sequence `$Bname$` contains the board name but also the vendor (when defined). 
Access sequence `$Dname$` only contains the device name and not the vendor (expected).

### Expected Behavior

`$Bname$` should contain only the board name as specified in the documentation.

[Access Sequences](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#access-sequences)
- `$Bname$`: [Bname](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#board-name-conventions) of the selected board as specified in the [board:](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#board) node.

### Steps To Reproduce

csolution.yml
```
  target-types:
    - type: STM32H745I-DISCO
      board: STMicroelectronics::STM32H745I-DISCO
      device: STMicroelectronics::STM32H745XIHx
```
cproject.yml
```
      files:
        - file: test_$Bname$.c
        - file: test_$Dname$.c
```
cbuild generates cbuild.yml
```
      files:
        - file: test_STMicroelectronics::STM32H745I-DISCO.c
          category: other
        - file: test_STM32H745XIHx.c
          category: sourceC
```

### Affected tools

- [X] cbuild
- [ ] cbuild2cmake
- [ ] cpackget
- [ ] csolution
- [ ] packchk
- [ ] svdconv

### Affected operating systems

- [ ] Windows amd64
- [ ] Windows arm64
- [ ] Linux amd64
- [ ] Linux arm64
- [ ] MacOS amd64
- [ ] MacOS arm64

### Environment

cmsis-toolbox 2.6.1
Windows 11
