### ISSUE TITLE
[Bug]: Manifest file has unknown versions

### ISSUE THREAD

**Issue by brondani** [Open-CMSIS-Pack/cmsis-toolbox#239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The `vidx2pidx` and `svdconv` tools have unknown versions in the [`manifest_2.7.0.yml`](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/releases/tag/2.7.0) file:
```
...
  svdconv:
    version: unknown
    sha256: 091cf321ed7c1bbe443ec81c4f615eb2820198ebb63427e2150f56f5958b0389
  vidx2pidx:
    version: unknown
    sha256: a90ec7ab80d93f1082205f7b1200f8a5cdf3f9db3a02bddaa798d415c3dba118
```

- `vidx2pidx` is not printing the version number: https://github.com/Open-CMSIS-Pack/vidx2pidx/issues/24
- `svdconv` does not support the `-V` flag used by the generate_manifest script to retrieve the tools versions:
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/2.7.0/scripts/generate_manifest.py#L50

### Expected Behavior

`svdconv` and/or `generate_manifest` script should be updated to correctly write all versions in the manifest file.

### Affected tools

- [ ] cbuild
- [ ] cbuild2cmake
- [ ] cpackget
- [ ] csolution
- [ ] packchk
- [X] svdconv

### Affected operating systems

- [ ] Windows amd64
- [ ] Windows arm64
- [ ] Linux amd64
- [ ] Linux arm64
- [ ] MacOS amd64
- [ ] MacOS arm64

**Comment by jkrech** [comment]
Manifest file from last nighty build:

manifest_2.7.0-37-g0829e02.yml
```
  ...
  svdconv:
    version: 3.3.47+p202
    sha256: ae568b8b0274fb26a43845dde0c091de98a679c69cc3b8e6203f0363ed465c33
  vidx2pidx:
    version: 0.0.4-11
    sha256: 8eb29d8a49e9d614177f2d423d10d1e0e54bdfed81145e2f4c988ab6b2531f24
```

All tool versions are correctly reported and collected.
