### ISSUE TITLE
[Bug][Regression]: CMSIS-Toolbox 2.7.0 breaks build with linker region headers generated by executes statements

### ISSUE THREAD

**Issue by EaselinkBachmann** [Open-CMSIS-Pack/cmsis-toolbox#245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`projmgr` rejects projects where linker region files are not found before building, even if those files would be generated by `executes` statements in CMake.

This behaviour was last changed in [devtools#1882](https://github.com/Open-CMSIS-Pack/devtools/pull/1882)

### Expected Behavior

`projmgr` should not reject projects where linker region files are not found before building if those files would be generated by `executes` statements in CMake. Alternatively, there should be a way to portably include generated files in the linker script preprocessing step, such as by adding include directories for the linker script preprocessing step.

The previous behaviour in cmsis-toolbox 2.6.1 (warning if such files are missing) was fine since the build was not actually stopped, and worked properly after the first build.

### Steps To Reproduce

This change breaks projects that generate their own region headers with an executes statement, for example:

```yaml
project:
  ...
  linker:
    - script: linker_script.sct.src
    - regions: $SolutionDir()$/common/include/project/generated/flash_layout.h
  ...
  executes:
    - execute: generate-flash-layout-header
      run: python $input(0)$ -o $output$
      input:
        - $SolutionDir()$/scripts/generate_flash_layout_header.py
        - $SolutionDir()$/scripts/flash_layout.py
      output:
        - $SolutionDir()$/common/include/project/generated/flash_layout.h
  ...
```

If `$SolutionDir()$/common/include/project/generated/flash_layout.h` doesn't already exists before the build is started, the build fails with `error csolution: specified regions header was not found`.

### Affected tools

- [X] cbuild
- [X] cbuild2cmake
- [ ] cpackget
- [ ] csolution
- [ ] packchk
- [ ] svdconv

### Affected operating systems

- [ ] Windows amd64
- [ ] Windows arm64
- [X] Linux amd64
- [ ] Linux arm64
- [ ] MacOS amd64
- [ ] MacOS arm64

### Environment

- Arch Linux
- CMSIS-Toolbox 2.7.0 and armclang 6.21.0 as distributed by vcpkg
