### ISSUE TITLE
[Bug]: CMSIS Solution project: I cannot set an input dependency on an INCBIN binary asset

### ISSUE THREAD

**Issue by MK-HTX** [Open-CMSIS-Pack/cmsis-toolbox#280]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

An assembler file that includes an INCBIN directive (e.g. an assembler file in an LPC55S69 CPU0 based project) is not automatically rebuilt if the binary asset included by an INCBIN directive changes (e.g. the binary generated by an LPC55S69 CPU1 based project).

### Expected Behavior

The AXF file for a project that contains INCBIN directives is rebuilt when there is a change to any INCBIN referenced binary assets.

### Steps To Reproduce

1. Create a dummy binary asset.
2. Add an INCBIN directive for the dummy binary asset to a assembler file in a project that builds successfully.
3. Build the project.
4. Modify the contents of the binary asset.
5. Rebuild theproject.

### Affected tools

- [x] cbuild
- [x] cbuild2cmake
- [ ] cpackget
- [x] csolution
- [ ] packchk
- [ ] svdconv

### Affected operating systems

- [ ] Windows amd64
- [ ] Windows arm64
- [ ] Linux amd64
- [ ] Linux arm64
- [ ] MacOS amd64
- [ ] MacOS arm64

**Comment by MK-HTX** [comment]
The following works, but having to touch a pack file seems wrong:

```
  executes:
    - execute: CopyCore1Image
      run: Cmake -E copy ${INPUT_0} ${OUTPUT_0}
      input:
        - $bin()$
      output:
        - $SolutionDir()$/Common/core1_image.bin
    - execute: INCBINCore1Image
      run: ${CMAKE_COMMAND} -E touch $output$
      input:
        - $SolutionDir()$/Common/core1_image.bin
      output:
        - $Pack(NXP::LPC55S69_DFP)$/devices/LPC55S69/utilities/incbin/fsl_incbin.S
```
