### ISSUE TITLE
Add `copied-from:` node to documentation and schema of the Solution YAML input file

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/cmsis-toolbox#366]
### Description

Add information recording the origin of a copied layer in the Solution YAML input file to the documentation and schema for `*.csolution.yml`

Example:
```
  target-types:
    - type: STM32U585AIIx
      variables:
        - SDSIO-Layer: $SolutionDir()$/sdsio/usb/sdsio_usb.clayer.yml
        - Board-Layer: $SolutionDir()$/Board/B-U585I-IOT02A/Board.clayer.yml
          copied-from: ${CMSIS_PACK_ROOT}/Keil/B-U585I-IOT02A_BSP/2.0.0/Layers/Default/Board.clayer.yml
      device: STM32U585AIIx
      board: B-U585I-IOT02A:Rev.C
```

Recording the origin of a layer alongside the variable specifying the `*.clayer.yml` destination, helps to track where the files that were copied from a pack version to the project originated from.

### Priority
Medium

### Related Issues (Optional)
https://github.com/ARM-software/vscode-cmsis-csolution/issues/177
