### ISSUE TITLE
[Feature]: Add support for setting custom configurations for Debuggers 

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/cmsis-toolbox#376]
### Description

Adding of key/value pairs is already accepted in the `csolution.yml` file.  For example:

```yml
  target-types:
    - type: AE722F80F55D5LS
      board: DevKit-E7:Gen 2
      device: AE722F80F55D5LS
      target-set:
        - set:
          images:
            - image: ./alif-sdk/build/zephyr/zephyr.elf
          debugger:
            name: CMSIS-DAP
            interface: SWD
            hprot: 0x09                       # this is a custom setting
```

Currently these settings are ignored.  

I suggest the following behavior:

- Default settings in [debug-adapters.yml](https://github.com/Open-CMSIS-Pack/debug-adapter-registry/blob/main/registry/debug-adapters.yml) provide init values, i.e. `hprot: 0x01`
- These values can be overwritten in `csolution.yml` as shown above
- The values are exported in `cbuild-run.yml`, the output would be in our example.

```yml
 debugger:
    name: CMSIS-DAP@pyOCD
    protocol: swd
    hprot: 0x09
    clock: 10000000
    start-pname: M55_HE
```

**Value Usage:**
- A debugger (i.e. pyOCD) could use directly the value from `cbuild-run.yml`
- VSCode Solution Extension could use such values to populate [template files](https://mdk-packs.github.io/vscode-cmsis-solution-docs/configuration.html#template-files). 

**Longer Term:**

The [debug-adapters.yml](https://github.com/Open-CMSIS-Pack/debug-adapter-registry/blob/main/registry/debug-adapters.yml) could be extended with `parameters:` that describes the parameters and their potential values.  This information could be used to:
 
- validate acceptable parameters
- populate a GUI to simplify debugger configuration.

### Priority

High

### Related Issues (Optional)

https://github.com/ARM-software/vscode-cmsis-csolution/issues/254#issuecomment-2949294858
https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/issues/357

### Is this request a Security Requirement?

- [ ] Yes
